[theme]
primaryColor = "#39FF14"      # Lime green
backgroundColor = "#0E1117"   # Dark mode background
secondaryBackgroundColor = "#262730"
textColor = "#FFFFFF"         # White text
font = "sans serif"
